theme: jekyll-theme-slate
baseurl: '/The-36-Lessons-of-Vivec/' # the subpath of your site, e.g. /blog
url: 'https://mmillar-bolis.github.io' # the base hostname & protocol for your site, e.g. http://example.com
title: 'The 36 Lessons of Vivec'
description: 'rendered in markdown with verse numbers and rubrics'
show_downloads: false
